import{a as n}from"./assets/vendor-DzcBeMgS.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();n.defaults.baseURL="https://dummyjson.com/recipes";async function d(){const{data:t}=await n();return t}async function l(t){const{data:o}=await n(`/${t}`);return o}const a={recipesList:document.querySelector(".recipes-list"),backdrop:document.querySelector(".backdrop")};function u(){a.backdrop.classList.remove(".hidden")}function p(t){const o=t.map(({image:c,name:s,difficulty:e,cuisine:r,id:i})=>`<li class="recipes-item">
            <img class="image" src="${c}" alt="${s}" data-id="${i}" />
            <div class="box">
              <h3 class="title">${s}</h3>
              <p class="text">Cuisine: ${r}</p>
              <p class="text">Difficulty: ${e}</p>
            </div>
          </li>`).join("");a.recipesList.innerHTML=o}async function f(){try{const{recipes:t}=await d();console.log(t),p(t)}catch(t){console.log("error",t)}}async function m(t){if(t.target.nodeName==="IMG")try{const o=t.target.dataset.id,c=await l(o);u()}catch(o){console.log("error",o)}}document.addEventListener("DOMContentLoaded",f);a.recipesList.addEventListener("click",m);
//# sourceMappingURL=index.js.map
